- package-lock.json
- package.json
- server/api/code.js
- server/api/index.js
> Added: route for code execution on backend

- client/components/codewars/Input.js
- client/routes.js
- client/store/codeReducer.js
- client/store/index.js
- package-lock.json
- package.json
- public/index.html
Ticket-#2
Able to take user input and submit input to backend
> able to submit the result-#2

- client/app.js
- client/components/codewars/AllQuestionPage.js
- client/components/codewars/Input.js
- client/components/navbar.js
- client/routes.js
- client/store/index.js
- client/store/questionReducer.js
- public/style.css
> Add navbar #20

- client/components/auth-form.js
- client/components/codewars/Input.js
- client/components/navbar.js
- client/store/user.js
- public/style.css
Task:
1. Modified Signup and login form.
2. Add welcome back on Navbar once user login.
3. Revise route (history push) after user login or signup back to question list page.
> addStylingtoSignUpPage

- client/store/questionReducer.js
- package.json
- script/seed.js
- server/api/index.js
- server/api/questions.js
- server/db/models/index.js
- server/db/models/question.js
> Added: questions model, api route, seed

- client/components/navbar.js
- script/seed.js
- server/db/models/question.js
> Added: test specs to model and seed

- client/components/codewars/AllQuestionPage.js
- client/components/codewars/Input.js
- client/routes.js
- client/store/user.spec.js
- package-lock.json
- package.json
- public/style.css
- script/seed.js
- server/api/code.js
- server/db/models/question.js
Tasks:
1. Add Text Editor
2. Fixed backend for the new text editor
3. Refactor logic for single question page
4. Add a bit styling in all question and single question page.
> Add code testing #30

- script/seed.js
- server/db/models/index.js
> user friends added to database

- server/auth/index.js
> login user eager loads friends

- client/components/codewars/Input.js
- client/store/user.js
- script/seed.js
- server/auth/index.js
> Add friends for user

- script/seed.js
- server/api/code.js
> Updated api post code route to reflect updated question model

- server/api/questions.js
- server/api/questions.spec.js
- server/api/users.spec.js
- server/db/models/question.spec.js
- server/db/models/user.spec.js
Updated user tests to incorporate updated model. Added tests for question model and all questions route.
> Backend unit tests

- client/app.js
- client/components/navbar.js
- client/store/questionReducer.js
- script/seed.js
- server/api/code.js
Tasks:
1. Add 6 questions with pre-populated function header.
2. Add input and expected output for all questions.
3. Modified current nested for loop comparison for user output vs expected output to JSON.stringtify method.
******* Every one need to reseed DB to restart.
> Add Real Question seeds to DB with inputs and expected output, also revised VM result testing comparison for array and Object

- server/api/code.js
> Fixed test code api route so that it works single argument functions

- client/components/codewars/Input.js
- client/store/codeReducer.js
- server/api/code.js
> Update test code route

- script/seed.js
Made a few minor changes to question descriptions in seed file.
---
> Updated: question descriptions in seed file

- client/components/codewars/AllQuestionPage.js
- client/components/navbar.js
- client/socket.js
- client/store/index.js
- client/store/warReducer.js
- server/socket/index.js
> Challenge button socket connect so when a user challenges another user, a challenge screen is rendered to other users. no other functionality yet.

- client/components/codewars/AllQuestionPage.js
- client/components/codewars/Input.js
- client/store/codeReducer.js
> disabled run button after user submit code for certain amount of time

- script/seed.js
- server/api/code.js
Made a minor change to code route api to fix bug affecting arrays with single items. Added seed questions and modified existing ones to fix bugs. 
---
> New questions

- package-lock.json
- package.json
- script/seed.js
- server/api/code.js
- server/codeSpecFiles/alphabetize.spec.js
- server/codeSpecFiles/balancedBracks.spec.js
- server/codeSpecFiles/insertInterval.spec.js
- server/codeSpecFiles/intersection.spec.js
- server/codeSpecFiles/largestNum.spec.js
- server/codeSpecFiles/medianNum.spec.js
- server/codeSpecFiles/nextLargestNum.spec.js
- server/codeSpecFiles/noVowels.spec.js
- server/codeSpecFiles/quantumMech.spec.js
- server/codeSpecFiles/replaceChar.spec.js
- server/codeSpecFiles/reverseWords.spec.js
- server/codeSpecFiles/twoSum.spec.js
- server/db/models/question.js
- server/index.js
> Connect docker to heroku server codebase #67

- client/components/codewars/QuestionLabel.js
- client/components/navbar.js
- client/store/questionReducer.js
> add Filter For difficulty level

- client/components/codewars/Input.js
- client/components/codewars/Multiply.js
- client/components/codewars/Result.js
- server/socket/index.js
> Reformat result terminal

- 1.patch
- client/components/auth-form.js
- client/components/navbar.js
- public/index.html
- script/seed.js
> Minor updates to seed file questions, sign-up screen, application name

- client/components/codewars/AllQuestionPage.js
- client/components/codewars/Chat.js
- client/components/codewars/FriendPopup.js
- client/components/codewars/Multiply.js
- client/components/navbar.js
- client/socket.js
- client/store/chatReducer.js
- client/store/index.js
- client/store/warReducer.js
- package-lock.json
- server/auth/index.js
- server/socket/index.js
> Socket rooms - functionality added for battle rooms: redux state for sockets, chat, and socket connections.

- client/components/codewars/AllQuestionPage.js
- client/components/codewars/Chat.js
- client/components/codewars/FriendPopup.js
- client/components/codewars/Multiply.js
> Update User Reducer for Chat after sockect online Connection

- client/components/codewars/AllQuestionPage.js
- client/components/codewars/Multiply.js
- client/components/codewars/Result.js
- client/socket.js
- client/store/codeReducer.js
- client/store/warReducer.js
- server/auth/index.js
- server/index.js
- server/socket/index.js
> Win condition operational

- client/components/codewars/Multiply.js
- server/socket/index.js
> Experimental branch nerfbuff featureset

- client/components/codewars/Chat.js
- client/store/chatReducer.js
- server/socket/index.js
> Chat interface

- client/routes.js
- server/api/questions.js
> Home page now redirects to all-questions page

- client/components/codewars/Multiply.js
- client/store/chatReducer.js
> Back to all question after win or loss

- client/components/codewars/Chat.js
- client/components/codewars/Multiply.js
- client/components/navbar.js
- public/style.css
> add new Style to multiply page

- public/style.css
> fixed styling

- server/socket/index.js
> Fixed server crashing bug upon challenger disconnect

- client/components/codewars/Multiply.js
> Extended winning timer to 10s

- client/components/codewars/FriendPopup.js
Replace the loader component with empty div for guest to fixed bug for constantly loader
> replace loader component with empty div for guest
